import Link from 'next/link'
import { cn } from '@/lib/utils'
import '../styles/globals.css'
import type { Metadata } from 'next'

import { Inter as FontSans } from 'next/font/google'
import { buttonVariants } from '@/components/ui/button'
import { Icons } from '@/components/icons'
import { ModeToggle } from '@/components/mode-toggle'
import { ThemeProvider } from '@/components/provider'

export const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<head />

			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased flex flex-col',
					fontSans.variable
				)}
			>
				<div className='max-w-xl mx-auto py-8'>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem
						disableTransitionOnChange
					>
						<header className='sticky z-50 w-full bg-background/95 backdrop-blur'>
							<div className='flex items-center justify-between py-4'>
								<a className='flex items-center space-x-2' href='/'>
									<div className='flex flex-col space-y-1 text-sm leading-none'>
										<span className='text-lg font-bold'>Duy Le</span>
										<span>Full Stack Developer</span>
									</div>
								</a>
								<div className='flex items-center space-x-1'>
									<Link href='/' target='_blank' rel='noreferrer'>
										<div
											className={cn(
												buttonVariants({
													variant: 'ghost'
												}),
												'w-8 px-0 h-8'
											)}
										>
											<Icons.gitHub className='h-4 w-4' />
											<span className='sr-only'>GitHub</span>
										</div>
									</Link>
									<ModeToggle />
								</div>
							</div>
						</header>
						<main className='flex-1'>{children}</main>
					</ThemeProvider>
				</div>
			</body>
		</html>
	)
}
