import Link from 'next/link'
import { cn } from '@/lib/utils'
import '../styles/globals.css'
import type { Metadata } from 'next'

import { Inter as FontSans } from 'next/font/google'
import { buttonVariants } from '@/components/ui/button'
import { Icons } from '@/components/icons'
import { ModeToggle } from '@/components/mode-toggle'
import { ThemeProvider } from '@/components/provider'

export const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' suppressHydrationWarning>
			<head />
			<body
				className={cn(
					'min-h-screen font-sans antialiased flex flex-col',
					fontSans.variable
				)}
			>
				{children}
			</body>
		</html>
	)
}
